import { GenealogyUser } from "@/components/genealogy";
import { UserRole, UserStatus } from "@/components/genealogy/types";

export const mockGenealogyData: GenealogyUser[] = [
  {
    id: "1",
    userId: 1001,
    fullName: "Alice Smith",
    userName: "alice.smith",
    email: "alice@example.com",
    avatar: "/images/avatars/Avatar=1.png",
    country: "USA",
    level: 0,
    role: UserRole.ADMIN,
    status: UserStatus.ACTIVE,
    createdAt: "2025-01-01T10:00:00Z",
    referralId: undefined,
    parentId: undefined,
  },
  {
    id: "2",
    userId: 1002,
    fullName: "Bob Johnson",
    userName: "bob.j",
    email: "bob@example.com",
    avatar: "/images/avatars/Avatar=2.png",
    country: "USA",
    level: 1,
    role: UserRole.USER,
    status: UserStatus.ACTIVE,
    createdAt: "2025-01-05T10:00:00Z",
    referralId: 1001,
    parentId: 1001,
  },
  {
    id: "3",
    userId: 1003,
    fullName: "Charlie Brown",
    userName: "charlie.b",
    email: "charlie@example.com",
    avatar: "/images/avatars/Avatar=3.png",
    country: "Canada",
    level: 1,
    role: UserRole.USER,
    status: UserStatus.ACTIVE,
    createdAt: "2025-01-06T12:00:00Z",
    referralId: 1001,
    parentId: 1001,
  },
  {
    id: "4",
    userId: 1004,
    fullName: "Diana Prince",
    userName: "diana.p",
    email: "diana@example.com",
    avatar: "/images/avatars/Avatar=4.png",
    country: "UK",
    level: 2,
    role: UserRole.USER,
    status: UserStatus.ACTIVE,
    createdAt: "2025-01-10T08:00:00Z",
    referralId: 1001,
    parentId: 1001,
  },
  {
    id: "5",
    userId: 1005,
    fullName: "Ethan Hunt",
    userName: "ethan.h",
    email: "ethan@example.com",
    avatar: "/images/avatars/Avatar=5.png",
    country: "USA",
    level: 2,
    role: UserRole.USER,
    status: UserStatus.ACTIVE,
    createdAt: "2025-01-12T09:00:00Z",
    referralId: 1001,
    parentId: 1001,
  },
  {
    id: "6",
    userId: 1006,
    fullName: "Fiona Gallagher",
    userName: "fiona.g",
    email: "fiona@example.com",
    avatar: "/images/avatars/Avatar=6.png",
    country: "Canada",
    level: 2,
    role: UserRole.USER,
    status: UserStatus.BLOCKED,
    createdAt: "2025-01-15T11:30:00Z",
    referralId: 1003,
    parentId: 1003,
  },
  {
    id: "7",
    userId: 1007,
    fullName: "George Clark",
    userName: "george.c",
    email: "george@example.com",
    avatar: "/images/avatars/Avatar=7.png",
    country: "UK",
    level: 3,
    role: UserRole.USER,
    status: UserStatus.ACTIVE,
    createdAt: "2025-01-18T13:00:00Z",
    referralId: 1004,
    parentId: 1004,
  },
  {
    id: "8",
    userId: 1008,
    fullName: "Hannah Lee",
    userName: "hannah.l",
    email: "hannah@example.com",
    avatar: "/images/avatars/Avatar=8.png",
    country: "Australia",
    level: 3,
    role: UserRole.USER,
    status: UserStatus.ACTIVE,
    createdAt: "2025-01-19T09:00:00Z",
    referralId: 1005,
    parentId: 1005,
  },
  {
    id: "9",
    userId: 1009,
    fullName: "Ian Wright",
    userName: "ian.w",
    email: "ian@example.com",
    avatar: "/images/avatars/Avatar=9.png",
    country: "USA",
    level: 3,
    role: UserRole.USER,
    status: UserStatus.ACTIVE,
    createdAt: "2025-01-20T15:00:00Z",
    referralId: 1006,
    parentId: 1006,
  },
  {
    id: "10",
    userId: 1010,
    fullName: "Jenny Kim",
    userName: "jenny.k",
    email: "jenny@example.com",
    avatar: "/images/avatars/Avatar=10.png",
    country: "Korea",
    level: 3,
    role: UserRole.USER,
    status: UserStatus.ACTIVE,
    createdAt: "2025-01-22T16:30:00Z",
    referralId: 1003,
    parentId: 1003,
  },

  {
    id: "11",
    userId: 1011,
    fullName: "Kevin Nash",
    userName: "kevin.n",
    email: "kevin@example.com",
    avatar: "/images/avatars/Avatar=1.png",
    country: "USA",
    level: 4,
    role: UserRole.USER,
    status: UserStatus.ACTIVE,
    createdAt: "2025-01-25T10:00:00Z",
    referralId: 1004,
    parentId: 1004,
  },
  {
    id: "12",
    userId: 1012,
    fullName: "Laura Palmer",
    userName: "laura.p",
    email: "laura@example.com",
    avatar: "/images/avatars/Avatar=2.png",
    country: "Canada",
    level: 4,
    role: UserRole.USER,
    status: UserStatus.ACTIVE,
    createdAt: "2025-01-26T11:30:00Z",
    referralId: 1004,
    parentId: 1004,
  },
  {
    id: "13",
    userId: 1013,
    fullName: "Mark Spencer",
    userName: "mark.s",
    email: "mark@example.com",
    avatar: "/images/avatars/Avatar=3.png",
    country: "UK",
    level: 4,
    role: UserRole.USER,
    status: UserStatus.BLOCKED,
    createdAt: "2025-01-27T14:00:00Z",
    referralId: 1006,
    parentId: 1006,
  },
  {
    id: "14",
    userId: 1014,
    fullName: "Natalie Portman",
    userName: "natalie.p",
    email: "natalie@example.com",
    avatar: "/images/avatars/Avatar=4.png",
    country: "USA",
    level: 4,
    role: UserRole.USER,
    status: UserStatus.ACTIVE,
    createdAt: "2025-01-28T09:00:00Z",
    referralId: 1006,
    parentId: 1006,
  },
  {
    id: "15",
    userId: 1015,
    fullName: "Oscar Wilde",
    userName: "oscar.w",
    email: "oscar@example.com",
    avatar: "/images/avatars/Avatar=5.png",
    country: "Ireland",
    level: 4,
    role: UserRole.USER,
    status: UserStatus.ACTIVE,
    createdAt: "2025-01-29T13:30:00Z",
    referralId: 1010,
    parentId: 1010,
  },
  {
    id: "16",
    userId: 1016,
    fullName: "Paula Dean",
    userName: "paula.d",
    email: "paula@example.com",
    avatar: "/images/avatars/Avatar=6.png",
    country: "USA",
    level: 5,
    role: UserRole.USER,
    status: UserStatus.ACTIVE,
    createdAt: "2025-02-01T10:00:00Z",
    referralId: 1011,
    parentId: 1011,
  },
  {
    id: "17",
    userId: 1017,
    fullName: "Quentin Blake",
    userName: "quentin.b",
    email: "quentin@example.com",
    avatar: "/images/avatars/Avatar=7.png",
    country: "UK",
    level: 5,
    role: UserRole.USER,
    status: UserStatus.BLOCKED,
    createdAt: "2025-02-02T12:45:00Z",
    referralId: 1012,
    parentId: 1012,
  },
  {
    id: "18",
    userId: 1018,
    fullName: "Rachel Green",
    userName: "rachel.g",
    email: "rachel@example.com",
    avatar: "/images/avatars/Avatar=8.png",
    country: "USA",
    level: 5,
    role: UserRole.USER,
    status: UserStatus.ACTIVE,
    createdAt: "2025-02-03T11:00:00Z",
    referralId: 1013,
    parentId: 1013,
  },
  {
    id: "19",
    userId: 1019,
    fullName: "Steve Rogers",
    userName: "steve.r",
    email: "steve@example.com",
    avatar: "/images/avatars/Avatar=9.png",
    country: "USA",
    level: 5,
    role: UserRole.USER,
    status: UserStatus.ACTIVE,
    createdAt: "2025-02-04T14:20:00Z",
    referralId: 1014,
    parentId: 1014,
  },
  {
    id: "20",
    userId: 1020,
    fullName: "Tina Fey",
    userName: "tina.f",
    email: "tina@example.com",
    avatar: "/images/avatars/Avatar=10.png",
    country: "USA",
    level: 5,
    role: UserRole.USER,
    status: UserStatus.ACTIVE,
    createdAt: "2025-02-05T15:30:00Z",
    referralId: 1006,
    parentId: 1006,
  },
];
