import { PaymentMethod } from "../types";

export const mockPaymentMethods: PaymentMethod[] = [
  {
    id: 1,
    name: "JamsrPay",
    logo: "/images/jamsrpay.png",
    description: "Limit 1 USD - 10,000 USD",
    minWithdraw: 100,
    maxWithdraw: 10000,
    charge: 1.5,
    gasFee: 0,
    arrives: "in seconds",
    isResently: true,
  },
  {
    id: 2,
    name: "BTCPay",
    logo: "/images/btcpay.png",
    description: "Limit 1 USD - 10,000 USD",
    minWithdraw: 100,
    maxWithdraw: 10000,
    charge: 2.5,
    gasFee: 0,
    arrives: "in seconds",
    isResently: true,
  },
  {
    id: 3,
    name: "Coingate",
    logo: "/images/coingate.png",
    description: "Limit 1 USD - 10,000 USD",
    minWithdraw: 100,
    maxWithdraw: 10000,
    charge: 1.5,
    gasFee: 0,
    arrives: "in seconds",
  },
  {
    id: 4,
    name: "Stripe",
    logo: "/images/stripe.jpeg",
    description: "Limit 1 USD - 10,000 USD",
    minWithdraw: 100,
    maxWithdraw: 10000,
    charge: 1.5,
    gasFee: 0,
    arrives: "in seconds",
  },
];
