import { Transaction, TransactionCategory, TransactionStatus } from "../types";

export const mockTransactions: Transaction[] = [
  {
    id: "txn_001",
    amount: 100.0,
    charge: 2.0,
    netAmount: 98.0,
    description: "Grocery shopping",
    status: TransactionStatus.DEBIT,
    category: TransactionCategory.WITHDRAW,
    userId: 101,
    createdAt: "2025-08-01T10:15:30Z",
    paymentMethodDetails: {
      name: "Visa",
      logo: "/icons/dashboard2/mastercard.svg",
    },
  },
  {
    id: "txn_002",
    amount: 200.0,
    charge: 0.0,
    netAmount: 200.0,
    description: "Salary credit",
    status: TransactionStatus.CREDIT,
    category: TransactionCategory.DEPOSIT,
    userId: 102,
    createdAt: "2025-08-01T11:00:00Z",
    paymentMethodDetails: {
      name: "Bank Transfer",
      logo: "/icons/dashboard2/EU.svg",
    },
  },
  {
    id: "txn_003",
    amount: 50.0,
    charge: 1.0,
    netAmount: 49.0,
    description: "Send to friend",
    status: TransactionStatus.CREDIT,
    category: TransactionCategory.PEER_TRANSFER,
    userId: 103,
    createdAt: "2025-07-31T16:20:00Z",
    paymentMethodDetails: {
      name: "PayPal",
      logo: "/icons/dashboard2/apple-music.svg",
    },
  },
  {
    id: "txn_004",
    amount: 150.0,
    charge: 2.5,
    netAmount: 147.5,
    description: "ATM withdrawal",
    status: TransactionStatus.FAILED,
    category: TransactionCategory.WITHDRAW,
    userId: 104,
    createdAt: "2025-07-30T09:45:00Z",
    paymentMethodDetails: {
      name: "Mastercard",
      logo: "/icons/dashboard2/mastercard.svg",
    },
  },
  {
    id: "txn_005",
    amount: 120.0,
    charge: 1.2,
    netAmount: 118.8,
    description: "Peer transfer",
    status: TransactionStatus.PENDING,
    category: TransactionCategory.PEER_TRANSFER,
    userId: 105,
    createdAt: "2025-08-02T08:10:00Z",
    paymentMethodDetails: {
      name: "Google Pay",
      logo: "/icons/dashboard2/mastercard.svg",
    },
  },
  {
    id: "txn_006",
    amount: 300.0,
    charge: 0.0,
    netAmount: 300.0,
    description: "Direct deposit",
    status: TransactionStatus.CREDIT,
    category: TransactionCategory.DEPOSIT,
    userId: 106,
    createdAt: "2025-07-29T17:00:00Z",
    paymentMethodDetails: {
      name: "Bank ACH",
      logo: "/icons/dashboard2/mastercard.svg",
    },
  },
  {
    id: "txn_007",
    amount: 75.0,
    charge: 0.75,
    netAmount: 74.25,
    description: "Dinner payment",
    status: TransactionStatus.DEBIT,
    category: TransactionCategory.PEER_TRANSFER,
    userId: 107,
    createdAt: "2025-08-01T21:30:00Z",
    paymentMethodDetails: {
      name: "Apple Pay",
      logo: "/icons/dashboard2/mastercard.svg",
    },
  },
  {
    id: "txn_008",
    amount: 500.0,
    charge: 5.0,
    netAmount: 495.0,
    description: "Bill payment",
    status: TransactionStatus.CREDIT,
    category: TransactionCategory.WITHDRAW,
    userId: 108,
    createdAt: "2025-08-02T14:50:00Z",
    paymentMethodDetails: {
      name: "NetBanking",
      logo: "/icons/dashboard2/mastercard.svg",
    },
  },
  {
    id: "txn_009",
    amount: 250.0,
    charge: 2.5,
    netAmount: 247.5,
    description: "Received from friend",
    status: TransactionStatus.CREDIT,
    category: TransactionCategory.PEER_TRANSFER,
    userId: 109,
    createdAt: "2025-07-30T12:00:00Z",
    paymentMethodDetails: {
      name: "Cash App",
      logo: "/icons/dashboard2/mastercard.svg",
    },
  },
  {
    id: "txn_010",
    amount: 80.0,
    charge: 0.8,
    netAmount: 79.2,
    description: "Coffee shop",
    status: TransactionStatus.DEBIT,
    category: TransactionCategory.WITHDRAW,
    userId: 110,
    createdAt: "2025-08-01T07:25:00Z",
    paymentMethodDetails: {
      name: "Stripe",
      logo: "/icons/dashboard2/mastercard.svg",
    },
  },
];
